# Generated by Django 6.0.6 on 2026-06-28 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('parent_mobile', models.CharField(blank=True, max_length=10)),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='students/aadhar/')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('address', models.TextField(blank=True)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('current_class', models.CharField(blank=True, choices=[('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('1st PUC', '1st PUC'), ('2nd PUC', '2nd PUC'), ('Completed PUC', 'Completed PUC'), ('NEET Repeater', 'NEET Repeater')], max_length=20)),
                ('board', models.CharField(blank=True, max_length=20)),
                ('year_of_passing', models.CharField(blank=True, max_length=4)),
                ('tenth_marks', models.CharField(blank=True, max_length=10)),
                ('puc1_marks', models.CharField(blank=True, max_length=10)),
                ('puc2_marks', models.CharField(blank=True, max_length=10)),
                ('previous_coaching', models.BooleanField(default=False)),
                ('institute_name', models.CharField(blank=True, max_length=200)),
                ('neet_attempt_status', models.CharField(blank=True, max_length=20)),
                ('attempt1_marks', models.CharField(blank=True, max_length=10)),
                ('attempt2_marks', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(blank=True, choices=[('AADHYA', 'AADHYA'), ('VISHWANATHA', 'VISHWANATHA'), ('VAIDYANATHA', 'VAIDYANATHA')], max_length=20)),
                ('hostel_required', models.BooleanField(default=False)),
                ('roll_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
