# Generated by Django 6.0.6 on 2026-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojas_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_class', models.CharField(blank=True, max_length=20)),
                ('program', models.CharField(blank=True, choices=[('AADHYA', 'AADHYA'), ('VISHWANATHA', 'VISHWANATHA'), ('VAIDYANATHA', 'VAIDYANATHA'), ('Not Sure', 'Not Sure')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
