# Generated by Django 6.0.6 on 2026-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojas_users', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_class',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('PUC 1', 'PUC 1'), ('PUC 2', 'PUC 2')], max_length=20),
        ),
    ]
