# Generated by Django 6.0.6 on 2026-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojas_users', '0003_alter_studentprofile_current_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
