# Generated by Django 6.0.6 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('ojas_users', '0004_studentprofile_require_password_change')]

    operations = [
        migrations.CreateModel(
            name='HomeLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()), ('end_date', models.DateField()), ('reason', models.TextField()),
                ('guardian_name', models.CharField(max_length=100)), ('guardian_mobile', models.CharField(max_length=10)), ('guardian_relation', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_leave_requests', to='ojas_users.studentprofile')),
            ],
            options={'verbose_name': 'Home Leave Request', 'verbose_name_plural': 'Home Leave Requests', 'ordering': ['-created_at']},
        ),
    ]