# Generated by Django 6.0.6 on 2026-07-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojas_users', '0005_homeleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=100)),
                ('number_of_visitors', models.PositiveSmallIntegerField(default=1)),
                ('visiting_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_visit_requests', to='ojas_users.studentprofile')),
            ],
            options={
                'verbose_name': 'Parent Visit Request',
                'verbose_name_plural': 'Parent Visit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
