import React, { useCallback, useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, Alert } from 'react-native';
import { Calendar } from 'react-native-calendars';
import api from '../../services/api';

const formatDate = (value) => value ? value.split('-').reverse().join('/') : '';

export default function ParentVisitScreen({ navigation }) {
  const [activeTab, setActiveTab] = useState('book');
  const [calendarVisible, setCalendarVisible] = useState(false);
  const [form, setForm] = useState({ visitDate: '', visitTime: '', parentName: '', parentPhone: '', relation: '', purpose: '', numberOfVisitors: '', visitingMessage: '' });
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(false);
  const relations = ['Father', 'Mother', 'Both Parents', 'Guardian'];
  const timeSlots = ['10:00 AM', '11:00 AM', '12:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'];
  const purposes = ['General Meeting', 'Academic Discussion', 'Fee Payment', 'Student Pickup', 'Other'];

  const loadRequests = useCallback(async () => { setLoading(true); try { const data = await api.getParentVisitRequests(); setRequests(data.requests || []); } catch (error) { Alert.alert('Could not load visits', error.message); } finally { setLoading(false); } }, []);
  useEffect(() => { loadRequests(); }, [loadRequests]);
  const submit = async () => {
    if (!form.visitDate || !form.visitTime || !form.parentName || !form.parentPhone || !form.relation || !form.purpose) { Alert.alert('Missing Info', 'Please fill all required fields'); return; }
    try { await api.submitParentVisitRequest({ visit_date: form.visitDate, visit_time: form.visitTime, parent_name: form.parentName, parent_mobile: form.parentPhone, relation: form.relation, purpose: form.purpose, number_of_visitors: form.numberOfVisitors || 1, visiting_message: form.visitingMessage }); await loadRequests(); setActiveTab('history'); setForm({ visitDate: '', visitTime: '', parentName: '', parentPhone: '', relation: '', purpose: '', numberOfVisitors: '', visitingMessage: '' }); } catch (error) { Alert.alert('Booking not submitted', error.message); }
  };
  const statusColor = (status) => status === 'approved' ? '#27AE60' : status === 'rejected' ? '#C0392B' : '#C9A227';
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  return <ScrollView style={styles.container}><View style={styles.header}><Text style={styles.headerLabel}>CAMPUS VISIT</Text><Text style={styles.headerTitle}>Parent Visit <Text style={styles.headerAccent}>Booking</Text></Text><View style={styles.ruleBox}><Text style={styles.ruleText}>Visit must be booked at least 1 day in advance</Text></View></View>
    <View style={styles.timings}><Text style={styles.timingTitle}>Visit Hours</Text><Text style={styles.timingText}>10 AM - 12 PM    |    2 PM - 5 PM</Text></View>
    <View style={styles.tabs}><TouchableOpacity style={[styles.tab, activeTab === 'book' && styles.active]} onPress={() => setActiveTab('book')}><Text>Book Visit</Text></TouchableOpacity><TouchableOpacity style={[styles.tab, activeTab === 'history' && styles.active]} onPress={() => setActiveTab('history')}><Text>Visit History</Text></TouchableOpacity></View>
    {activeTab === 'book' ? <View style={styles.form}><Text style={styles.label}>Visit Date *</Text><TouchableOpacity style={styles.dateButton} onPress={() => setCalendarVisible(!calendarVisible)}><Text>{form.visitDate ? formatDate(form.visitDate) : 'Select from calendar'}</Text></TouchableOpacity>{calendarVisible && <Calendar minDate={tomorrow} onDayPress={(day) => { setForm({ ...form, visitDate: day.dateString }); setCalendarVisible(false); }} theme={{ selectedDayBackgroundColor: '#1A3A6C', arrowColor: '#1A3A6C' }} />}
      <Text style={styles.label}>Preferred Time *</Text><View style={styles.wrap}>{timeSlots.map((item) => <TouchableOpacity key={item} style={[styles.chip, form.visitTime === item && styles.selected]} onPress={() => setForm({ ...form, visitTime: item })}><Text>{item}</Text></TouchableOpacity>)}</View>
      <Input label="Parent/Guardian Name *" value={form.parentName} onChangeText={(v) => setForm({ ...form, parentName: v })} /><Input label="Parent Mobile *" value={form.parentPhone} keyboardType="numeric" onChangeText={(v) => setForm({ ...form, parentPhone: v })} />
      <Text style={styles.label}>Relation *</Text><View style={styles.wrap}>{relations.map((item) => <TouchableOpacity key={item} style={[styles.chip, form.relation === item && styles.selected]} onPress={() => setForm({ ...form, relation: item })}><Text>{item}</Text></TouchableOpacity>)}</View>
      <Text style={styles.label}>Purpose of Visit *</Text><View style={styles.wrap}>{purposes.map((item) => <TouchableOpacity key={item} style={[styles.chip, form.purpose === item && styles.selected]} onPress={() => setForm({ ...form, purpose: item })}><Text>{item}</Text></TouchableOpacity>)}</View>
      <Input label="Number of Visitors" value={form.numberOfVisitors} keyboardType="numeric" onChangeText={(v) => setForm({ ...form, numberOfVisitors: v })} /><Input label="Visiting Message (optional)" value={form.visitingMessage} multiline onChangeText={(v) => setForm({ ...form, visitingMessage: v })} />
      <TouchableOpacity style={styles.submit} onPress={submit}><Text style={styles.submitText}>Book Parent Visit</Text></TouchableOpacity></View> : <View style={styles.history}>{loading && <Text>Loading requests...</Text>}{!loading && requests.length === 0 && <Text style={styles.empty}>No visit history yet</Text>}{requests.map((item) => <View key={item.id} style={styles.card}><View style={styles.row}><View><Text style={styles.date}>{item.date} at {item.time}</Text><Text>{item.parent_name} ({item.relation})</Text></View><Text style={[styles.status, { color: statusColor(item.status) }]}>{item.status.toUpperCase()}</Text></View><Text>Purpose: {item.purpose}</Text>{!!item.admin_comment && <Text style={styles.note}>Admin note: {item.admin_comment}</Text>}</View>)}</View>}
    <TouchableOpacity style={styles.dashboard} onPress={() => navigation.navigate('StudentHome')}><Text style={styles.submitText}>Back to Dashboard</Text></TouchableOpacity></ScrollView>;
}
function Input({ label, ...props }) { return <View><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, props.multiline && styles.area]} placeholderTextColor="#9CA3AF" {...props} /></View>; }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F8FAFF'},header:{backgroundColor:'#1A3A6C',padding:24},headerLabel:{fontSize:11,letterSpacing:3,color:'#C9A227'},headerTitle:{fontSize:24,fontWeight:'700',color:'#fff',marginVertical:8},headerAccent:{color:'#C9A227'},ruleBox:{padding:10,backgroundColor:'rgba(201,162,39,.2)',borderRadius:8},ruleText:{color:'#C9A227'},timings:{margin:16,padding:16,backgroundColor:'#fff',borderRadius:8},timingTitle:{fontWeight:'700',fontSize:15},timingText:{marginTop:8,color:'#1A3A6C'},tabs:{flexDirection:'row',backgroundColor:'#fff'},tab:{flex:1,alignItems:'center',padding:14,borderBottomWidth:2,borderColor:'transparent'},active:{borderColor:'#1A3A6C'},form:{padding:20},label:{fontWeight:'600',color:'#1A3A6C',marginTop:14,marginBottom:6},input:{borderWidth:1,borderColor:'#E5E7EB',borderRadius:8,padding:12,backgroundColor:'#fff',fontSize:14},dateButton:{borderWidth:1,borderColor:'#E5E7EB',borderRadius:8,padding:12,backgroundColor:'#fff'},area:{minHeight:80,textAlignVertical:'top'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{padding:10,borderWidth:1,borderColor:'#E5E7EB',borderRadius:8,backgroundColor:'#fff'},selected:{borderColor:'#1A3A6C',backgroundColor:'#EBF3FF'},submit:{padding:16,alignItems:'center',backgroundColor:'#1A3A6C',borderRadius:8,marginTop:24},dashboard:{margin:16,padding:16,alignItems:'center',backgroundColor:'#1A3A6C',borderRadius:8},submitText:{color:'#fff',fontWeight:'700'},history:{padding:16},empty:{textAlign:'center',padding:28,color:'#6B7280'},card:{backgroundColor:'#fff',padding:16,borderRadius:8,marginBottom:12},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},date:{fontWeight:'700',color:'#0F2548'},status:{fontSize:11,fontWeight:'700'},note:{marginTop:7,color:'#3D5278'}});